services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cockroachdb1:26257, cockroachdb2:26257/defaultdb?sslmode=disable&loadBalanceHosts=true
    depends_on:
      - cockroachdb1
      - cockroachdb2
    restart: on-failure
    #command: ["sh", "-c", "/usr/app/create_crt.sh && java -jar app.jar"]
    networks:
      - cockNet

  cockroachdb1:
    image: cockroachdb/cockroach:v21.1.7
    command: start --insecure --certs-dir=/cockroach/cockroach-certs --join=cockroachdb1,cockroachdb2 --listen-addr=cockroachdb1:26257 --advertise-addr=cockroachdb1:26257
    volumes:
      - cockroachdb_data1:/cockroach/cockroach-data
    ports:
      - "26257:26257"
      - "8081:8080"
    restart: always
    networks:
      - cockNet

  cockroachdb2:
    image: cockroachdb/cockroach:v21.1.7
    command: start --insecure --certs-dir=/cockroach/cockroach-certs --join=cockroachdb1,cockroachdb2 --listen-addr=cockroachdb2:26257 --advertise-addr=cockroachdb2:26257
    volumes:
      - cockroachdb_data2:/cockroach/cockroach-data
    ports:
      - "26258:26257"
      - "8082:8080"
    restart: always
    networks:
      - cockNet


volumes:
  cockroachdb_data1:
  cockroachdb_data2:

networks:
  cockNet: