services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://delantaldeestrellas-9799.7tc.aws-eu-central-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&password=W0rCJoi77QV71AJ2Kx8w4g&user=alvaro&loadBalanceHosts=true
      - SPRING_DATASOURCE_USERNAME=alvaro
      - SPRING_DATASOURCE_PASSWORD=W0rCJoi77QV71AJ2Kx8w4g
    depends_on:
      - cockroachdb1
      - cockroachdb2
    restart: on-failure
    command: ["sh", "-c", "/usr/app/create_crt.sh && java -jar app.jar"]

  cockroachdb1:
    image: cockroachdb/cockroach:v21.1.7
    command: start --insecure --join=cockroachdb1,cockroachdb2 --listen-addr=:26257 --advertise-addr=:26257
    volumes:
      - cockroachdb_data1:/cockroach/cockroach-data
    ports:
      - "26257:26257"
      - "8081:8080"
    restart: always

  cockroachdb2:
    image: cockroachdb/cockroach:v21.1.7
    command: start --insecure --join=cockroachdb1,cockroachdb2 --listen-addr=:26257 --advertise-addr=:26257
    volumes:
      - cockroachdb_data2:/cockroach/cockroach-data
    ports:
      - "26258:26257"
      - "8082:8080"
    restart: always

volumes:
  cockroachdb_data1:
  cockroachdb_data2: